//AccessModifier DeclarationClass ClassName {}
public class LearnVariableTypes {
    
    //Variables 
    //(DataType)  Name;
    
    //Primitive Datatype Integer, string, Date, Doulbe, Float, DateTime, Boolean, Blob, Id, Decimal, sObject.
    
                                             // vamsi                ''        Null 
    string name = 'vamsi';                       // name = 'Vamsi';       name = '';    name;
    integer RollNo = 24;
    integer temp = -12;
    Double tempDenver = 12.34;
    string standard = 'B-Tech';
    Boolean TenthPass = False; 
    Account acc;
    Itenary__c itenary;
    
    //Complex Datatype (Collections)
    list<string> NameList = new list<string>{'chary','vamsi','Ranganth'};
    //NameList.add('Chary');
    //NameList.add('vamsi');
    //NameList.add('Ranganath');
    
    
    //methods

}